# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-21 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_event_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_api',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
