# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-21 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20170615_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.BigIntegerField(unique=True)),
                ('start_time', models.BigIntegerField()),
                ('venue_display', models.IntegerField()),
                ('venue_name', models.CharField(max_length=200)),
                ('venue_address', models.CharField(max_length=200)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('region_name', models.CharField(max_length=200)),
                ('city_name', models.CharField(max_length=200)),
                ('country_name', models.CharField(max_length=200)),
                ('all_day', models.IntegerField()),
            ],
        ),
    ]
